application: hackalackin
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/
  static_dir: static
  secure: always

- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
